version: "3.9"
services:
    multitenant.demo2.web:
        build:
          context: .
          dockerfile: MultiTenantDemo2/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - multitenant.demo2.db
    multitenant.demo2.db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"